ARG PORTER_VERSION
ARG REGISTRY
FROM alpine:3.15 as builder
ARG PLUGIN_VERSION
COPY --chown=65532:65532 bin/plugins/kubernetes/$PLUGIN_VERSION/kubernetes-linux-amd64 /kubernetes

FROM $REGISTRY/porter-agent:$PORTER_VERSION
COPY --from=builder --chown=65532:65532 /kubernetes /app/.porter/plugins/kubernetes/kubernetes

