name: Build
on: [workflow_dispatch, push, pull_request]

env:
  MAGEFILE_VERBOSE: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum
      - name: Set up Mage
        run: go run mage.go ConfigureAgent
      - name: Build
        run: mage Build
      - name: Test
        run: mage Test
      - name: Publish
        if: ${{ github.event_name == 'push' }}
        run: mage Publish
        env:
            GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}